name: Binge Companion Data Api

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r binge-companion-data-api/requirements-dev.txt
      - name: Lint with flake8
        run: |
          # Stops the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Start Tests with coverage
        env:
          RDB_USER: postgres
          RDB_PASSWORD: postgres
          RDB_HOST: localhost
          RDB_DATABASE_NAME: postgres
        run: |
          coverage run -m pytest
          coverage lcov
        working-directory: binge-companion-data-api/
      - name: Publish coverage to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: binge-companion-data-api/coverage.lcov
